# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2, 26.2)
java_version=25
neo_form_version=26.1.2-1

fabric_version=0.19.2
fabric_api_version=0.150.0+26.1.2
neo_version=26.1.2.60-beta
neo_version_range=[26.1.2.21-beta,)

# Mod Properties
mod_id=morevillages
mod_name=More Villages
license=ARR
version=1.0
group=com.newjumper.morevillages
mod_author=NewJumperr
description=Adds more villages
